import mongoose from 'mongoose';

export const getEmployeeProfileFields = (employeeRef) => ({
  employeeCode: { type: String, default: '' },
  profilePhoto: { type: String, default: '' },
  gender: { type: String, enum: ['Male', 'Female', 'Other', ''], default: '' },
  dateOfBirth: { type: Date },
  maritalStatus: { type: String, enum: ['Single', 'Married', 'Divorced', 'Widowed', ''], default: '' },
  bloodGroup: { type: String, default: '' },
  personalEmail: { type: String, default: '' },
  personalMobile: { type: String, default: '' },
  employeeType: { type: String, enum: ['Permanent', 'Contract', 'Intern', ''], default: 'Permanent' },
  probationEndDate: { type: Date },
  employmentStatus: { type: String, enum: ['Active', 'Resigned', 'Terminated', 'Inactive'], default: 'Active' },
  reportingManager: { type: mongoose.Schema.Types.ObjectId, ref: employeeRef, default: null },
  workLocation: { type: String, default: '' },
  currentAddress: { type: String, default: '' },
  permanentAddress: { type: String, default: '' },
  emergencyContact: {
    name: { type: String, default: '' },
    number: { type: String, default: '' },
    relationship: { type: String, default: '' },
  },
  officialMobile: { type: String, default: '' },
  companyIdCardNumber: { type: String, default: '' },
  workShift: { type: String, default: '' },
  attendancePolicy: { type: String, default: '' },
  documents: {
    resume: { type: String, default: '' },
    offerLetter: { type: String, default: '' },
    appointmentLetter: { type: String, default: '' },
    ndaAgreement: { type: String, default: '' },
    experienceLetters: { type: String, default: '' },
    educationalCertificates: { type: String, default: '' },
    panCard: { type: String, default: '' },
    aadhaarCard: { type: String, default: '' },
    passport: { type: String, default: '' },
    drivingLicense: { type: String, default: '' },
    bankPassbook: { type: String, default: '' },
  },
  salaryPayroll: {
    ctc: { type: Number, default: 0 },
    grossSalary: { type: Number, default: 0 },
    basicSalary: { type: Number, default: 0 },
    hra: { type: Number, default: 0 },
    da: { type: Number, default: 0 },
    conveyance: { type: Number, default: 0 },
    specialAllowance: { type: Number, default: 0 },
    medicalAllowance: { type: Number, default: 0 },
    attendanceIncentive: { type: Number, default: 0 },
    allowances: { type: Number, default: 0 },
    bonus: { type: Number, default: 0 },
    employerPf: { type: Number, default: 0 },
    employeePf: { type: Number, default: 0 },
    professionalTax: { type: Number, default: 0 },
    tds: { type: Number, default: 0 },
    totalDeductions: { type: Number, default: 0 },
    netSalary: { type: Number, default: 0 },
    monthlyCTC: { type: Number, default: 0 },
    annualCTC: { type: Number, default: 0 },
    components: [{ code: String, name: String, amount: Number }],
    deductions: [{ code: String, name: String, amount: Number }],
    employerContributions: [{ code: String, name: String, amount: Number }],
    pfNumber: { type: String, default: '' },
    esicNumber: { type: String, default: '' },
    uanNumber: { type: String, default: '' },
    panNumber: { type: String, default: '' },
    taxInformation: { type: String, default: '' },
    bankAccountDetails: { type: String, default: '' },
  },
  performance: {
    kpis: [{ type: String }],
    reviews: [{ date: Date, rating: Number, comments: String }],
    appraisalHistory: [{ date: Date, score: Number, notes: String }],
    goals: [{ title: String, status: String, dueDate: Date }],
    managerFeedback: [{ date: Date, feedback: String }],
  },
  skills: {
    skills: [{ type: String }],
    technologies: [{ type: String }],
    certifications: [{ name: String, issuer: String, year: Number }],
    trainingCompleted: [{ title: String, date: Date }],
    languages: [{ type: String }],
  },
  assets: {
    laptop: { type: String, default: '' },
    desktop: { type: String, default: '' },
    mobilePhone: { type: String, default: '' },
    simCard: { type: String, default: '' },
    accessCards: { type: String, default: '' },
    other: { type: String, default: '' },
  },
  access: {
    crmRole: { type: String, default: '' },
    permissions: [{ type: String }],
    sidebarSections: [{ type: String }],
    loginHistory: [{ date: Date, ip: String }],
    lastLogin: { type: Date },
    accountStatus: { type: String, enum: ['Active', 'Inactive', 'Locked'], default: 'Active' },
  },
  notes: {
    hrNotes: { type: String, default: '' },
    employeeRemarks: { type: String, default: '' },
    activityLog: [{ date: Date, action: String, by: String }],
    documentUploadHistory: [{ date: Date, document: String, uploadedBy: String }],
    profileUpdateHistory: [{ date: Date, field: String, updatedBy: String }],
  },
});
