export const MODULE_META = {
  deals: { title: 'Deals', section: 'CRM', description: 'Track deal stages, values, and close rates across your sales pipeline.' },
  quotations: { title: 'Quotations', section: 'CRM', description: 'Create and manage quotations sent to prospects and clients.' },
  milestones: { title: 'Milestones', section: 'Projects', description: 'Define and monitor project milestones and delivery checkpoints.' },
  timesheets: { title: 'Timesheets', section: 'Projects', description: 'Log and approve time spent on projects and tasks.' },
  performance: { title: 'Performance', section: 'Employees', description: 'Review employee goals, ratings, and performance cycles.' },
  assets: { title: 'Assets', section: 'Employees', description: 'Manage company assets assigned to employees.' },
  gst: { title: 'GST / Taxes', section: 'Finance', description: 'Configure tax rates, GST filings, and compliance records.' },
  products: { title: 'Products', section: 'Inventory', description: 'Maintain your product catalog and SKUs.' },
  stock: { title: 'Stock', section: 'Inventory', description: 'Monitor stock levels, warehouses, and inventory movements.' },
  'purchase-orders': { title: 'Purchase Orders', section: 'Inventory', description: 'Create and track purchase orders with suppliers.' },
  suppliers: { title: 'Suppliers', section: 'Inventory', description: 'Manage supplier contacts and procurement relationships.' },
  orders: { title: 'Orders', section: 'Sales', description: 'View and fulfill customer sales orders.' },
  email: { title: 'Email', section: 'Marketing', description: 'Plan and send email marketing campaigns.' },
  sms: { title: 'SMS', section: 'Marketing', description: 'Run SMS campaigns and transactional messages.' },
  whatsapp: { title: 'WhatsApp', section: 'Marketing', description: 'Manage WhatsApp broadcasts and customer chats.' },
  files: { title: 'Files', section: 'Documents', description: 'Store and organize company documents and uploads.' },
  contracts: { title: 'Contracts', section: 'Documents', description: 'Track client and vendor contracts with renewal dates.' },
  policies: { title: 'Policies', section: 'Documents', description: 'Publish HR and company policies for employees.' },
  chat: { title: 'Chat', section: 'Communication', description: 'Team chat and direct messaging.' },
  announcements: { title: 'Announcements', section: 'Communication', description: 'Company-wide announcements and notices.' },
  departments: { title: 'Departments', section: 'Administration', description: 'Organize teams and department hierarchy.' },
  designations: { title: 'Designations', section: 'Administration', description: 'Manage job titles and designation profiles.' },
}
